# Generated by Django 2.1.7 on 2019-03-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomies',
            old_name='title',
            new_name='bill',
        ),
        migrations.RemoveField(
            model_name='roomies',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='roomies',
            name='description',
        ),
        migrations.AddField(
            model_name='roomies',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
            preserve_default=False,
        ),
    ]
